package taskmaster.Model.DAOUtilities;
/**
 *
 * @author MR_JLTC
 */
public enum QUERY {
    INSERT_TASKINFO("INSERT INTO TASKINFO(BID, Task) VALUES(?,?)"),
    INSERT_BUCKETLIST_INFO("INSERT INTO BUCKETLIST_INFO(Name) VALUES(?)"),
    
    UPDATE_TASKINFO("UPDATE TASKINFO SET TASK=? WHERE TID=?"),
    UPDATE_BUCKETLIST_INFO("UPDATE BUCKETLIST_INFO SET NAME=? WHERE BID=?"),
    
    DELETE_TASKINFO("DELETE FROM TASKINFO WHERE TID=?"),
    DELETE_TASKINFO_DIRECTLY_FROM_BUCKETLIST("DELETE FROM TASKINFO WHERE BID=?"),
    DELETE_BUCKETLIST_INFO("DELETE FROM BUCKETLIST_INFO WHERE BID=?"),
    
    FETCH_BUCKETLIST_ID("SELECT BID FROM BUCKETLIST_INFO WHERE NAME=?"),
    FETCH_TASKINFO_ID("SELECT TID FROM TASK_INFO_VIEWER WHERE Task=? AND BUCKETLIST=?"),
    FETCH_TASKINFO_FROM_VIEWER("SELECT TASK FROM TASK_INFO_VIEWER WHERE BUCKETLIST=?"),
    SEARCH_BUCKETLIST_INFO("SELECT NAME FROM BUCKETLIST_INFO WHERE NAME=?"),
    FETCH_BUCKETLIST_INFO("SELECT NAME FROM BUCKETLIST_INFO");
    
    private final String s;
    
    QUERY(String s){
        this.s = s;
    }
    
    public String getQuery(){
        return this.s;
    }
}
